// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateAuthAttribute represents an attribute to be created
type CreateAuthAttribute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attribute     string                 `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Op            string                 `protobuf:"bytes,3,opt,name=op,proto3" json:"op,omitempty"` // Default: ":=" for radcheck, "+=" for radreply
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAuthAttribute) Reset() {
	*x = CreateAuthAttribute{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthAttribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthAttribute) ProtoMessage() {}

func (x *CreateAuthAttribute) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthAttribute.ProtoReflect.Descriptor instead.
func (*CreateAuthAttribute) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAuthAttribute) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *CreateAuthAttribute) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateAuthAttribute) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

// AuthCreateAttrResponse represents created attribute information
type AuthCreateAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Attribute     string                 `protobuf:"bytes,2,opt,name=attribute,proto3" json:"attribute,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Op            string                 `protobuf:"bytes,4,opt,name=op,proto3" json:"op,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthCreateAttrResponse) Reset() {
	*x = AuthCreateAttrResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthCreateAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthCreateAttrResponse) ProtoMessage() {}

func (x *AuthCreateAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthCreateAttrResponse.ProtoReflect.Descriptor instead.
func (*AuthCreateAttrResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *AuthCreateAttrResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AuthCreateAttrResponse) GetAttribute() string {
	if x != nil {
		return x.Attribute
	}
	return ""
}

func (x *AuthCreateAttrResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *AuthCreateAttrResponse) GetOp() string {
	if x != nil {
		return x.Op
	}
	return ""
}

// Create authentication credentials request
type CreateAuthRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Username        string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password        string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Attributes      []*CreateAuthAttribute `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	ReplyAttributes []*CreateAuthAttribute `protobuf:"bytes,4,rep,name=reply_attributes,json=replyAttributes,proto3" json:"reply_attributes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAuthRequest) Reset() {
	*x = CreateAuthRequest{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthRequest) ProtoMessage() {}

func (x *CreateAuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthRequest.ProtoReflect.Descriptor instead.
func (*CreateAuthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAuthRequest) GetAttributes() []*CreateAuthAttribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateAuthRequest) GetReplyAttributes() []*CreateAuthAttribute {
	if x != nil {
		return x.ReplyAttributes
	}
	return nil
}

// Create authentication credentials response
type CreateAuthResponse struct {
	state           protoimpl.MessageState    `protogen:"open.v1"`
	Username        string                    `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password        string                    `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Attributes      []*AuthCreateAttrResponse `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	ReplyAttributes []*AuthCreateAttrResponse `protobuf:"bytes,4,rep,name=reply_attributes,json=replyAttributes,proto3" json:"reply_attributes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateAuthResponse) Reset() {
	*x = CreateAuthResponse{}
	mi := &file_api_proto_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAuthResponse) ProtoMessage() {}

func (x *CreateAuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAuthResponse.ProtoReflect.Descriptor instead.
func (*CreateAuthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAuthResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateAuthResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAuthResponse) GetAttributes() []*AuthCreateAttrResponse {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateAuthResponse) GetReplyAttributes() []*AuthCreateAttrResponse {
	if x != nil {
		return x.ReplyAttributes
	}
	return nil
}

var File_api_proto_auth_auth_proto protoreflect.FileDescriptor

const file_api_proto_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x19api/proto/auth/auth.proto\x12\x04auth\"Y\n" +
	"\x13CreateAuthAttribute\x12\x1c\n" +
	"\tattribute\x18\x01 \x01(\tR\tattribute\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x0e\n" +
	"\x02op\x18\x03 \x01(\tR\x02op\"l\n" +
	"\x16AuthCreateAttrResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1c\n" +
	"\tattribute\x18\x02 \x01(\tR\tattribute\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x0e\n" +
	"\x02op\x18\x04 \x01(\tR\x02op\"\xcc\x01\n" +
	"\x11CreateAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x129\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x19.auth.CreateAuthAttributeR\n" +
	"attributes\x12D\n" +
	"\x10reply_attributes\x18\x04 \x03(\v2\x19.auth.CreateAuthAttributeR\x0freplyAttributes\"\xd3\x01\n" +
	"\x12CreateAuthResponse\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12<\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x1c.auth.AuthCreateAttrResponseR\n" +
	"attributes\x12G\n" +
	"\x10reply_attributes\x18\x04 \x03(\v2\x1c.auth.AuthCreateAttrResponseR\x0freplyAttributes2N\n" +
	"\vAuthService\x12?\n" +
	"\n" +
	"CreateAuth\x12\x17.auth.CreateAuthRequest\x1a\x18.auth.CreateAuthResponseB Z\x1evibe-ddd-golang/api/proto/authb\x06proto3"

var (
	file_api_proto_auth_auth_proto_rawDescOnce sync.Once
	file_api_proto_auth_auth_proto_rawDescData []byte
)

func file_api_proto_auth_auth_proto_rawDescGZIP() []byte {
	file_api_proto_auth_auth_proto_rawDescOnce.Do(func() {
		file_api_proto_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_auth_auth_proto_rawDesc), len(file_api_proto_auth_auth_proto_rawDesc)))
	})
	return file_api_proto_auth_auth_proto_rawDescData
}

var file_api_proto_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_auth_auth_proto_goTypes = []any{
	(*CreateAuthAttribute)(nil),    // 0: auth.CreateAuthAttribute
	(*AuthCreateAttrResponse)(nil), // 1: auth.AuthCreateAttrResponse
	(*CreateAuthRequest)(nil),      // 2: auth.CreateAuthRequest
	(*CreateAuthResponse)(nil),     // 3: auth.CreateAuthResponse
}
var file_api_proto_auth_auth_proto_depIdxs = []int32{
	0, // 0: auth.CreateAuthRequest.attributes:type_name -> auth.CreateAuthAttribute
	0, // 1: auth.CreateAuthRequest.reply_attributes:type_name -> auth.CreateAuthAttribute
	1, // 2: auth.CreateAuthResponse.attributes:type_name -> auth.AuthCreateAttrResponse
	1, // 3: auth.CreateAuthResponse.reply_attributes:type_name -> auth.AuthCreateAttrResponse
	2, // 4: auth.AuthService.CreateAuth:input_type -> auth.CreateAuthRequest
	3, // 5: auth.AuthService.CreateAuth:output_type -> auth.CreateAuthResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_auth_auth_proto_init() }
func file_api_proto_auth_auth_proto_init() {
	if File_api_proto_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_auth_auth_proto_rawDesc), len(file_api_proto_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_auth_auth_proto_goTypes,
		DependencyIndexes: file_api_proto_auth_auth_proto_depIdxs,
		MessageInfos:      file_api_proto_auth_auth_proto_msgTypes,
	}.Build()
	File_api_proto_auth_auth_proto = out.File
	file_api_proto_auth_auth_proto_goTypes = nil
	file_api_proto_auth_auth_proto_depIdxs = nil
}
