// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: api/proto/nas/nas.proto

package nas

import (
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NAS (Network Access Server) message
type NAS struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nasname         string                 `protobuf:"bytes,2,opt,name=nasname,proto3" json:"nasname,omitempty"`
	Shortname       string                 `protobuf:"bytes,3,opt,name=shortname,proto3" json:"shortname,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Ports           int32                  `protobuf:"varint,5,opt,name=ports,proto3" json:"ports,omitempty"`
	Secret          string                 `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	Server          string                 `protobuf:"bytes,7,opt,name=server,proto3" json:"server,omitempty"`
	Community       string                 `protobuf:"bytes,8,opt,name=community,proto3" json:"community,omitempty"`
	Description     string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	RequireMa       string                 `protobuf:"bytes,10,opt,name=require_ma,json=requireMa,proto3" json:"require_ma,omitempty"`
	LimitProxyState string                 `protobuf:"bytes,11,opt,name=limit_proxy_state,json=limitProxyState,proto3" json:"limit_proxy_state,omitempty"`
	CreatedAt       *timestamp.Timestamp   `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamp.Timestamp   `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NAS) Reset() {
	*x = NAS{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NAS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NAS) ProtoMessage() {}

func (x *NAS) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NAS.ProtoReflect.Descriptor instead.
func (*NAS) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{0}
}

func (x *NAS) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NAS) GetNasname() string {
	if x != nil {
		return x.Nasname
	}
	return ""
}

func (x *NAS) GetShortname() string {
	if x != nil {
		return x.Shortname
	}
	return ""
}

func (x *NAS) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *NAS) GetPorts() int32 {
	if x != nil {
		return x.Ports
	}
	return 0
}

func (x *NAS) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *NAS) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *NAS) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *NAS) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *NAS) GetRequireMa() string {
	if x != nil {
		return x.RequireMa
	}
	return ""
}

func (x *NAS) GetLimitProxyState() string {
	if x != nil {
		return x.LimitProxyState
	}
	return ""
}

func (x *NAS) GetCreatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *NAS) GetUpdatedAt() *timestamp.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Create NAS request
type CreateNASRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Nasname         string                 `protobuf:"bytes,1,opt,name=nasname,proto3" json:"nasname,omitempty"`
	Shortname       string                 `protobuf:"bytes,2,opt,name=shortname,proto3" json:"shortname,omitempty"`
	Type            string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Ports           int32                  `protobuf:"varint,4,opt,name=ports,proto3" json:"ports,omitempty"`
	Secret          string                 `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"`
	Server          string                 `protobuf:"bytes,6,opt,name=server,proto3" json:"server,omitempty"`
	Community       string                 `protobuf:"bytes,7,opt,name=community,proto3" json:"community,omitempty"`
	Description     string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	RequireMa       string                 `protobuf:"bytes,9,opt,name=require_ma,json=requireMa,proto3" json:"require_ma,omitempty"`
	LimitProxyState string                 `protobuf:"bytes,10,opt,name=limit_proxy_state,json=limitProxyState,proto3" json:"limit_proxy_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateNASRequest) Reset() {
	*x = CreateNASRequest{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNASRequest) ProtoMessage() {}

func (x *CreateNASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNASRequest.ProtoReflect.Descriptor instead.
func (*CreateNASRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{1}
}

func (x *CreateNASRequest) GetNasname() string {
	if x != nil {
		return x.Nasname
	}
	return ""
}

func (x *CreateNASRequest) GetShortname() string {
	if x != nil {
		return x.Shortname
	}
	return ""
}

func (x *CreateNASRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateNASRequest) GetPorts() int32 {
	if x != nil {
		return x.Ports
	}
	return 0
}

func (x *CreateNASRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *CreateNASRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *CreateNASRequest) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *CreateNASRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateNASRequest) GetRequireMa() string {
	if x != nil {
		return x.RequireMa
	}
	return ""
}

func (x *CreateNASRequest) GetLimitProxyState() string {
	if x != nil {
		return x.LimitProxyState
	}
	return ""
}

// Create NAS response
type CreateNASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nas           *NAS                   `protobuf:"bytes,1,opt,name=nas,proto3" json:"nas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNASResponse) Reset() {
	*x = CreateNASResponse{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNASResponse) ProtoMessage() {}

func (x *CreateNASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNASResponse.ProtoReflect.Descriptor instead.
func (*CreateNASResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{2}
}

func (x *CreateNASResponse) GetNas() *NAS {
	if x != nil {
		return x.Nas
	}
	return nil
}

// Get NAS request
type GetNASRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNASRequest) Reset() {
	*x = GetNASRequest{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNASRequest) ProtoMessage() {}

func (x *GetNASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNASRequest.ProtoReflect.Descriptor instead.
func (*GetNASRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{3}
}

func (x *GetNASRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Get NAS response
type GetNASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nas           *NAS                   `protobuf:"bytes,1,opt,name=nas,proto3" json:"nas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNASResponse) Reset() {
	*x = GetNASResponse{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNASResponse) ProtoMessage() {}

func (x *GetNASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNASResponse.ProtoReflect.Descriptor instead.
func (*GetNASResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{4}
}

func (x *GetNASResponse) GetNas() *NAS {
	if x != nil {
		return x.Nas
	}
	return nil
}

// NAS filter for list operations
type NASFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nasname       string                 `protobuf:"bytes,1,opt,name=nasname,proto3" json:"nasname,omitempty"`
	Shortname     string                 `protobuf:"bytes,2,opt,name=shortname,proto3" json:"shortname,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NASFilter) Reset() {
	*x = NASFilter{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NASFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NASFilter) ProtoMessage() {}

func (x *NASFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NASFilter.ProtoReflect.Descriptor instead.
func (*NASFilter) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{5}
}

func (x *NASFilter) GetNasname() string {
	if x != nil {
		return x.Nasname
	}
	return ""
}

func (x *NASFilter) GetShortname() string {
	if x != nil {
		return x.Shortname
	}
	return ""
}

func (x *NASFilter) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// List NAS request
type ListNASRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Filter        *NASFilter             `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNASRequest) Reset() {
	*x = ListNASRequest{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNASRequest) ProtoMessage() {}

func (x *ListNASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNASRequest.ProtoReflect.Descriptor instead.
func (*ListNASRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{6}
}

func (x *ListNASRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNASRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListNASRequest) GetFilter() *NASFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// List NAS response
type ListNASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nas           []*NAS                 `protobuf:"bytes,1,rep,name=nas,proto3" json:"nas,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNASResponse) Reset() {
	*x = ListNASResponse{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNASResponse) ProtoMessage() {}

func (x *ListNASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNASResponse.ProtoReflect.Descriptor instead.
func (*ListNASResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{7}
}

func (x *ListNASResponse) GetNas() []*NAS {
	if x != nil {
		return x.Nas
	}
	return nil
}

func (x *ListNASResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListNASResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListNASResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

// Update NAS request
type UpdateNASRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nasname         string                 `protobuf:"bytes,2,opt,name=nasname,proto3" json:"nasname,omitempty"`
	Shortname       string                 `protobuf:"bytes,3,opt,name=shortname,proto3" json:"shortname,omitempty"`
	Type            string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Ports           int32                  `protobuf:"varint,5,opt,name=ports,proto3" json:"ports,omitempty"`
	Secret          string                 `protobuf:"bytes,6,opt,name=secret,proto3" json:"secret,omitempty"`
	Server          string                 `protobuf:"bytes,7,opt,name=server,proto3" json:"server,omitempty"`
	Community       string                 `protobuf:"bytes,8,opt,name=community,proto3" json:"community,omitempty"`
	Description     string                 `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	RequireMa       string                 `protobuf:"bytes,10,opt,name=require_ma,json=requireMa,proto3" json:"require_ma,omitempty"`
	LimitProxyState string                 `protobuf:"bytes,11,opt,name=limit_proxy_state,json=limitProxyState,proto3" json:"limit_proxy_state,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateNASRequest) Reset() {
	*x = UpdateNASRequest{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNASRequest) ProtoMessage() {}

func (x *UpdateNASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNASRequest.ProtoReflect.Descriptor instead.
func (*UpdateNASRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateNASRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateNASRequest) GetNasname() string {
	if x != nil {
		return x.Nasname
	}
	return ""
}

func (x *UpdateNASRequest) GetShortname() string {
	if x != nil {
		return x.Shortname
	}
	return ""
}

func (x *UpdateNASRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateNASRequest) GetPorts() int32 {
	if x != nil {
		return x.Ports
	}
	return 0
}

func (x *UpdateNASRequest) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *UpdateNASRequest) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *UpdateNASRequest) GetCommunity() string {
	if x != nil {
		return x.Community
	}
	return ""
}

func (x *UpdateNASRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateNASRequest) GetRequireMa() string {
	if x != nil {
		return x.RequireMa
	}
	return ""
}

func (x *UpdateNASRequest) GetLimitProxyState() string {
	if x != nil {
		return x.LimitProxyState
	}
	return ""
}

// Update NAS response
type UpdateNASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nas           *NAS                   `protobuf:"bytes,1,opt,name=nas,proto3" json:"nas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNASResponse) Reset() {
	*x = UpdateNASResponse{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNASResponse) ProtoMessage() {}

func (x *UpdateNASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNASResponse.ProtoReflect.Descriptor instead.
func (*UpdateNASResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateNASResponse) GetNas() *NAS {
	if x != nil {
		return x.Nas
	}
	return nil
}

// Delete NAS request
type DeleteNASRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNASRequest) Reset() {
	*x = DeleteNASRequest{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNASRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNASRequest) ProtoMessage() {}

func (x *DeleteNASRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNASRequest.ProtoReflect.Descriptor instead.
func (*DeleteNASRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteNASRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Delete NAS response
type DeleteNASResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteNASResponse) Reset() {
	*x = DeleteNASResponse{}
	mi := &file_api_proto_nas_nas_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteNASResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteNASResponse) ProtoMessage() {}

func (x *DeleteNASResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_nas_nas_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteNASResponse.ProtoReflect.Descriptor instead.
func (*DeleteNASResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_nas_nas_proto_rawDescGZIP(), []int{11}
}

func (x *DeleteNASResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_nas_nas_proto protoreflect.FileDescriptor

const file_api_proto_nas_nas_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/nas/nas.proto\x12\x03nas\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa8\x03\n" +
	"\x03NAS\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\anasname\x18\x02 \x01(\tR\anasname\x12\x1c\n" +
	"\tshortname\x18\x03 \x01(\tR\tshortname\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05ports\x18\x05 \x01(\x05R\x05ports\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\tR\x06secret\x12\x16\n" +
	"\x06server\x18\a \x01(\tR\x06server\x12\x1c\n" +
	"\tcommunity\x18\b \x01(\tR\tcommunity\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"require_ma\x18\n" +
	" \x01(\tR\trequireMa\x12*\n" +
	"\x11limit_proxy_state\x18\v \x01(\tR\x0flimitProxyState\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaf\x02\n" +
	"\x10CreateNASRequest\x12\x18\n" +
	"\anasname\x18\x01 \x01(\tR\anasname\x12\x1c\n" +
	"\tshortname\x18\x02 \x01(\tR\tshortname\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05ports\x18\x04 \x01(\x05R\x05ports\x12\x16\n" +
	"\x06secret\x18\x05 \x01(\tR\x06secret\x12\x16\n" +
	"\x06server\x18\x06 \x01(\tR\x06server\x12\x1c\n" +
	"\tcommunity\x18\a \x01(\tR\tcommunity\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"require_ma\x18\t \x01(\tR\trequireMa\x12*\n" +
	"\x11limit_proxy_state\x18\n" +
	" \x01(\tR\x0flimitProxyState\"/\n" +
	"\x11CreateNASResponse\x12\x1a\n" +
	"\x03nas\x18\x01 \x01(\v2\b.nas.NASR\x03nas\"\x1f\n" +
	"\rGetNASRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\",\n" +
	"\x0eGetNASResponse\x12\x1a\n" +
	"\x03nas\x18\x01 \x01(\v2\b.nas.NASR\x03nas\"W\n" +
	"\tNASFilter\x12\x18\n" +
	"\anasname\x18\x01 \x01(\tR\anasname\x12\x1c\n" +
	"\tshortname\x18\x02 \x01(\tR\tshortname\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"i\n" +
	"\x0eListNASRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12&\n" +
	"\x06filter\x18\x03 \x01(\v2\x0e.nas.NASFilterR\x06filter\"t\n" +
	"\x0fListNASResponse\x12\x1a\n" +
	"\x03nas\x18\x01 \x03(\v2\b.nas.NASR\x03nas\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\xbf\x02\n" +
	"\x10UpdateNASRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x18\n" +
	"\anasname\x18\x02 \x01(\tR\anasname\x12\x1c\n" +
	"\tshortname\x18\x03 \x01(\tR\tshortname\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x14\n" +
	"\x05ports\x18\x05 \x01(\x05R\x05ports\x12\x16\n" +
	"\x06secret\x18\x06 \x01(\tR\x06secret\x12\x16\n" +
	"\x06server\x18\a \x01(\tR\x06server\x12\x1c\n" +
	"\tcommunity\x18\b \x01(\tR\tcommunity\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"require_ma\x18\n" +
	" \x01(\tR\trequireMa\x12*\n" +
	"\x11limit_proxy_state\x18\v \x01(\tR\x0flimitProxyState\"/\n" +
	"\x11UpdateNASResponse\x12\x1a\n" +
	"\x03nas\x18\x01 \x01(\v2\b.nas.NASR\x03nas\"\"\n" +
	"\x10DeleteNASRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"-\n" +
	"\x11DeleteNASResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xa9\x02\n" +
	"\n" +
	"NASService\x12:\n" +
	"\tCreateNAS\x12\x15.nas.CreateNASRequest\x1a\x16.nas.CreateNASResponse\x121\n" +
	"\x06GetNAS\x12\x12.nas.GetNASRequest\x1a\x13.nas.GetNASResponse\x124\n" +
	"\aListNAS\x12\x13.nas.ListNASRequest\x1a\x14.nas.ListNASResponse\x12:\n" +
	"\tUpdateNAS\x12\x15.nas.UpdateNASRequest\x1a\x16.nas.UpdateNASResponse\x12:\n" +
	"\tDeleteNAS\x12\x15.nas.DeleteNASRequest\x1a\x16.nas.DeleteNASResponseB;Z9github.com/novriyantoAli/freeradius-service/api/proto/nasb\x06proto3"

var (
	file_api_proto_nas_nas_proto_rawDescOnce sync.Once
	file_api_proto_nas_nas_proto_rawDescData []byte
)

func file_api_proto_nas_nas_proto_rawDescGZIP() []byte {
	file_api_proto_nas_nas_proto_rawDescOnce.Do(func() {
		file_api_proto_nas_nas_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_nas_nas_proto_rawDesc), len(file_api_proto_nas_nas_proto_rawDesc)))
	})
	return file_api_proto_nas_nas_proto_rawDescData
}

var file_api_proto_nas_nas_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_nas_nas_proto_goTypes = []any{
	(*NAS)(nil),                 // 0: nas.NAS
	(*CreateNASRequest)(nil),    // 1: nas.CreateNASRequest
	(*CreateNASResponse)(nil),   // 2: nas.CreateNASResponse
	(*GetNASRequest)(nil),       // 3: nas.GetNASRequest
	(*GetNASResponse)(nil),      // 4: nas.GetNASResponse
	(*NASFilter)(nil),           // 5: nas.NASFilter
	(*ListNASRequest)(nil),      // 6: nas.ListNASRequest
	(*ListNASResponse)(nil),     // 7: nas.ListNASResponse
	(*UpdateNASRequest)(nil),    // 8: nas.UpdateNASRequest
	(*UpdateNASResponse)(nil),   // 9: nas.UpdateNASResponse
	(*DeleteNASRequest)(nil),    // 10: nas.DeleteNASRequest
	(*DeleteNASResponse)(nil),   // 11: nas.DeleteNASResponse
	(*timestamp.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_api_proto_nas_nas_proto_depIdxs = []int32{
	12, // 0: nas.NAS.created_at:type_name -> google.protobuf.Timestamp
	12, // 1: nas.NAS.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: nas.CreateNASResponse.nas:type_name -> nas.NAS
	0,  // 3: nas.GetNASResponse.nas:type_name -> nas.NAS
	5,  // 4: nas.ListNASRequest.filter:type_name -> nas.NASFilter
	0,  // 5: nas.ListNASResponse.nas:type_name -> nas.NAS
	0,  // 6: nas.UpdateNASResponse.nas:type_name -> nas.NAS
	1,  // 7: nas.NASService.CreateNAS:input_type -> nas.CreateNASRequest
	3,  // 8: nas.NASService.GetNAS:input_type -> nas.GetNASRequest
	6,  // 9: nas.NASService.ListNAS:input_type -> nas.ListNASRequest
	8,  // 10: nas.NASService.UpdateNAS:input_type -> nas.UpdateNASRequest
	10, // 11: nas.NASService.DeleteNAS:input_type -> nas.DeleteNASRequest
	2,  // 12: nas.NASService.CreateNAS:output_type -> nas.CreateNASResponse
	4,  // 13: nas.NASService.GetNAS:output_type -> nas.GetNASResponse
	7,  // 14: nas.NASService.ListNAS:output_type -> nas.ListNASResponse
	9,  // 15: nas.NASService.UpdateNAS:output_type -> nas.UpdateNASResponse
	11, // 16: nas.NASService.DeleteNAS:output_type -> nas.DeleteNASResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_nas_nas_proto_init() }
func file_api_proto_nas_nas_proto_init() {
	if File_api_proto_nas_nas_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_nas_nas_proto_rawDesc), len(file_api_proto_nas_nas_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_nas_nas_proto_goTypes,
		DependencyIndexes: file_api_proto_nas_nas_proto_depIdxs,
		MessageInfos:      file_api_proto_nas_nas_proto_msgTypes,
	}.Build()
	File_api_proto_nas_nas_proto = out.File
	file_api_proto_nas_nas_proto_goTypes = nil
	file_api_proto_nas_nas_proto_depIdxs = nil
}
