// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.12.4
// source: api/proto/nas/nas.proto

package nas

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NASService_CreateNAS_FullMethodName = "/nas.NASService/CreateNAS"
	NASService_GetNAS_FullMethodName    = "/nas.NASService/GetNAS"
	NASService_ListNAS_FullMethodName   = "/nas.NASService/ListNAS"
	NASService_UpdateNAS_FullMethodName = "/nas.NASService/UpdateNAS"
	NASService_DeleteNAS_FullMethodName = "/nas.NASService/DeleteNAS"
)

// NASServiceClient is the client API for NASService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NASServiceClient interface {
	// Create a new NAS
	CreateNAS(ctx context.Context, in *CreateNASRequest, opts ...grpc.CallOption) (*CreateNASResponse, error)
	// Get a NAS by ID
	GetNAS(ctx context.Context, in *GetNASRequest, opts ...grpc.CallOption) (*GetNASResponse, error)
	// List NAS with pagination and filtering
	ListNAS(ctx context.Context, in *ListNASRequest, opts ...grpc.CallOption) (*ListNASResponse, error)
	// Update a NAS
	UpdateNAS(ctx context.Context, in *UpdateNASRequest, opts ...grpc.CallOption) (*UpdateNASResponse, error)
	// Delete a NAS
	DeleteNAS(ctx context.Context, in *DeleteNASRequest, opts ...grpc.CallOption) (*DeleteNASResponse, error)
}

type nASServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNASServiceClient(cc grpc.ClientConnInterface) NASServiceClient {
	return &nASServiceClient{cc}
}

func (c *nASServiceClient) CreateNAS(ctx context.Context, in *CreateNASRequest, opts ...grpc.CallOption) (*CreateNASResponse, error) {
	out := new(CreateNASResponse)
	err := c.cc.Invoke(ctx, NASService_CreateNAS_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nASServiceClient) GetNAS(ctx context.Context, in *GetNASRequest, opts ...grpc.CallOption) (*GetNASResponse, error) {
	out := new(GetNASResponse)
	err := c.cc.Invoke(ctx, NASService_GetNAS_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nASServiceClient) ListNAS(ctx context.Context, in *ListNASRequest, opts ...grpc.CallOption) (*ListNASResponse, error) {
	out := new(ListNASResponse)
	err := c.cc.Invoke(ctx, NASService_ListNAS_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nASServiceClient) UpdateNAS(ctx context.Context, in *UpdateNASRequest, opts ...grpc.CallOption) (*UpdateNASResponse, error) {
	out := new(UpdateNASResponse)
	err := c.cc.Invoke(ctx, NASService_UpdateNAS_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nASServiceClient) DeleteNAS(ctx context.Context, in *DeleteNASRequest, opts ...grpc.CallOption) (*DeleteNASResponse, error) {
	out := new(DeleteNASResponse)
	err := c.cc.Invoke(ctx, NASService_DeleteNAS_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NASServiceServer is the server API for NASService service.
// All implementations should embed UnimplementedNASServiceServer
// for forward compatibility
type NASServiceServer interface {
	// Create a new NAS
	CreateNAS(context.Context, *CreateNASRequest) (*CreateNASResponse, error)
	// Get a NAS by ID
	GetNAS(context.Context, *GetNASRequest) (*GetNASResponse, error)
	// List NAS with pagination and filtering
	ListNAS(context.Context, *ListNASRequest) (*ListNASResponse, error)
	// Update a NAS
	UpdateNAS(context.Context, *UpdateNASRequest) (*UpdateNASResponse, error)
	// Delete a NAS
	DeleteNAS(context.Context, *DeleteNASRequest) (*DeleteNASResponse, error)
}

// UnimplementedNASServiceServer should be embedded to have forward compatible implementations.
type UnimplementedNASServiceServer struct {
}

func (UnimplementedNASServiceServer) CreateNAS(context.Context, *CreateNASRequest) (*CreateNASResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNAS not implemented")
}
func (UnimplementedNASServiceServer) GetNAS(context.Context, *GetNASRequest) (*GetNASResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNAS not implemented")
}
func (UnimplementedNASServiceServer) ListNAS(context.Context, *ListNASRequest) (*ListNASResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNAS not implemented")
}
func (UnimplementedNASServiceServer) UpdateNAS(context.Context, *UpdateNASRequest) (*UpdateNASResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNAS not implemented")
}
func (UnimplementedNASServiceServer) DeleteNAS(context.Context, *DeleteNASRequest) (*DeleteNASResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNAS not implemented")
}

// UnsafeNASServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NASServiceServer will
// result in compilation errors.
type UnsafeNASServiceServer interface {
	mustEmbedUnimplementedNASServiceServer()
}

func RegisterNASServiceServer(s grpc.ServiceRegistrar, srv NASServiceServer) {
	s.RegisterService(&NASService_ServiceDesc, srv)
}

func _NASService_CreateNAS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NASServiceServer).CreateNAS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NASService_CreateNAS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NASServiceServer).CreateNAS(ctx, req.(*CreateNASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NASService_GetNAS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NASServiceServer).GetNAS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NASService_GetNAS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NASServiceServer).GetNAS(ctx, req.(*GetNASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NASService_ListNAS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NASServiceServer).ListNAS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NASService_ListNAS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NASServiceServer).ListNAS(ctx, req.(*ListNASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NASService_UpdateNAS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NASServiceServer).UpdateNAS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NASService_UpdateNAS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NASServiceServer).UpdateNAS(ctx, req.(*UpdateNASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NASService_DeleteNAS_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNASRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NASServiceServer).DeleteNAS(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NASService_DeleteNAS_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NASServiceServer).DeleteNAS(ctx, req.(*DeleteNASRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NASService_ServiceDesc is the grpc.ServiceDesc for NASService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NASService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nas.NASService",
	HandlerType: (*NASServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNAS",
			Handler:    _NASService_CreateNAS_Handler,
		},
		{
			MethodName: "GetNAS",
			Handler:    _NASService_GetNAS_Handler,
		},
		{
			MethodName: "ListNAS",
			Handler:    _NASService_ListNAS_Handler,
		},
		{
			MethodName: "UpdateNAS",
			Handler:    _NASService_UpdateNAS_Handler,
		},
		{
			MethodName: "DeleteNAS",
			Handler:    _NASService_DeleteNAS_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/nas/nas.proto",
}
